# Generated by Django 4.2.7 on 2026-02-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_karma',
        ),
    ]
